# Generated by Django 5.1.15 on 2026-03-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Whether this account has been anonymized after deletion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_anonymized'], name='users_user_is_anon_d8a8a7_idx'),
        ),
    ]
