# Generated by Django 6.0.2 on 2026-03-04 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full title of the book', max_length=500)),
                ('subtitle', models.CharField(blank=True, help_text='Book subtitle, if any', max_length=500, null=True)),
                ('authors', models.JSONField(default=list, help_text='List of author names')),
                ('isbn_13', models.CharField(blank=True, help_text='13-digit International Standard Book Number', max_length=13, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('isbn_10', models.CharField(blank=True, help_text='10-digit International Standard Book Number', max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('google_books_id', models.CharField(blank=True, help_text='Unique identifier from Google Books API', max_length=100, null=True, unique=True)),
                ('publisher', models.CharField(blank=True, help_text='Book publisher', max_length=200, null=True)),
                ('published_date', models.DateField(blank=True, help_text='Date of publication', null=True)),
                ('page_count', models.IntegerField(blank=True, help_text='Total number of pages', null=True)),
                ('description', models.TextField(blank=True, help_text='Book description or synopsis', null=True)),
                ('categories', models.JSONField(default=list, help_text='List of genres/categories')),
                ('cover_image_url', models.URLField(blank=True, help_text='URL to high-resolution cover image', max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to small thumbnail image', max_length=500, null=True)),
                ('is_indie', models.BooleanField(default=False, help_text='True for user-submitted indie books, False for API imports')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this book was added to the library')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this book (null for API-imported books)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['google_books_id'], name='books_book_google__da53e2_idx'), models.Index(fields=['is_indie'], name='books_book_is_indi_8a5ea5_idx'), models.Index(fields=['slug'], name='books_book_slug_ca552e_idx')],
            },
        ),
    ]
