# Generated by Django 6.0.2 on 2026-03-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_added_at_book_added_by_book_is_indie'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=100, unique=True),
        ),
    ]
