# Generated by Django 6.0.2 on 2026-03-04 19:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating from 0-5 stars (half-star increments allowed)', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Brief summary of the review', max_length=200)),
                ('content', models.TextField(help_text='Detailed review content')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the review (auto-generated)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this review was last updated')),
                ('book', models.ForeignKey(help_text='Book being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(help_text='User who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'), models.Index(fields=['user', 'book'], name='reviews_rev_user_id_8dce99_idx'), models.Index(fields=['slug'], name='reviews_rev_slug_bc1500_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
